### ISSUE TITLE
#Bypass the Windows Defender Checks (with 3rd Party AV)

### ISSUE THREAD

**Issue by Saltinbank-SyS** [HotCakeX/Harden-Windows-Security#103]
Hi Lady, sorry to bother you ...

I want to ask you if there is an option to bypass the checks and the message saying that WD is in passive mode (asking to remove 3rd party AV) ?
Thank you for the tool and the wiki (lot of interresting stuff to know about).

Thank you in advance.
Cheers, Saltinbank.

**Comment by HotCakeX** [comment]
hi, the code is simply making sure all the [requirements](https://github.com/HotCakeX/Harden-Windows-Security?tab=readme-ov-file#requirements-) are met.

3rd party AVs are totally unnecessary as Microsoft Defender and all of the features the module turns on are superior, but also not compatible with other AVs, users tried to combine 3rd party AVs with the module and had incompatibility issues.

If there is even a single scenario where a 3rd party AV caught something but MDAV after applying this module didn't, let me know so we can think about something else. So far, it's been always the other way around, the built-in features in Windows that the module turns on have been so much better than any 3rd party vendor's product. This also reduces your attack surface because you don't have to install anything or worry about vulnerabilities and bugs in that software that can be exploited.

Thank you ^^

**Comment by alexanderb0001** [comment]
Ive been told by https://maldroid.dev that a 3rd party AV is superior because malware with administration privileges can undo all the Microsoft Defender settings configured in the Group Policy editor or configured via DefenderUI.com , and that for administrative malware to do this with a 3rd party AV (like Sophos Home or Bit defender) the malware would need kernel level access to undo its protections, making the 3rd party AV superior.

Is this not true?
