### ISSUE TITLE
[Bug]: File explorer displays black bar on devices after running hardening script

### ISSUE THREAD

**Issue by starraiderx** [HotCakeX/Harden-Windows-Security#139]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

**Description:**
I've encountered an issue with the file explorer on all four devices where I've applied the hardening script. After approximately a month of using the script, the file explorer started showing a black bar (refer to the attached screenshot). While I understand this might not be directly related to the script, I was wondering if anyone else has experienced this or has a potential solution. For reference, devices that haven't had the script run on them are functioning as expected.

**Additional Information:**

- I have already tried troubleshooting using both DISM and SFC tools.

- Affected Win Versions: 22621

- As a quick fix: Running the unprotect script fixes the issue mentioned

Kind regards

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/33199500/b3f415b9-19cc-4143-897c-69b7a1b3fa22)

**Comment by HotCakeX** [comment]
The only thing i can think of to tell you to try (if you haven't already) is to remove exploit protections for `explorer.exe` and restart it or your system, then see if you can still reproduce this issue. You can remove it using GUI for Microsoft Defender.

That's the only thing that is sorta non-standard and done by trial and errors.

**Comment by HotCakeX** [comment]
This issue is very similar to this one: https://github.com/HotCakeX/Harden-Windows-Security/issues/115

I resolved it by removing the problematic mitigation, but apparently that wasn't enough as you're experiencing the same issue.

I'm going to remove all of the process mitigations for `explorer.exe`. They can be added again in the future once we figure out what the most stable and bug-free mitigations for it are, after like 2 months of constant testing.

**Comment by HotCakeX** [comment]
I just released an update that should fix this issue: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.1.9

**Comment by HotCakeX** [comment]
Closing this as complete. Please run any of the module's cmdlets to auto update it and then run Microsoft Defender category using `protect-WindowsSecurity` cmdlet, it will remove Explorer.exe process mitigations, if any, while reapplying all other process mitigations.

In the update I also added an optional parameter to easily remove process mitigations only without removing any other hardening measures. `Unprotect-WindowsSecurity -OnlyProcessMitigations`

Feel free to reopen if the issue still persists.

**Comment by starraiderx** [comment]
Apologies for the delayed feedback; I couldn't test it yesterday. The issue seems to have been resolved with commit `837daaf8e7e5cd7243ea7a83f7740258918c65ac`. It appears that CFG was the underlying cause of the observed bug.

For future reference, if you come across a bug, rather than simply removing the mitigation, please consider setting them to their default value or inverting them.

**Comment by HotCakeX** [comment]
> Apologies for my delayed response; I couldn't test it out yesterday. The issue seems to have been addressed with commit [837daaf](https://github.com/HotCakeX/Harden-Windows-Security/commit/837daaf8e7e5cd7243ea7a83f7740258918c65ac). It appears the CFG was the root cause of the observed bug.
> 
> For future reference, instead of simply removing a mitigation upon encountering a bug, consider setting them to their default or the inverse value. Like you did in commit [15d4488](https://github.com/HotCakeX/Harden-Windows-Security/commit/15d4488196d3af079c293e51e16d464f01f901c5).
> 
> With the aforementioned fix, you can now safely revert commit [cd5db7c](https://github.com/HotCakeX/Harden-Windows-Security/commit/cd5db7cdd7f9ea7910f62fbc025384488931f6c1).
> 
> Kind regards

But I fixed [that issue](https://github.com/HotCakeX/Harden-Windows-Security/issues/115) over a month ago. If you ran the Microsoft Defender category in the past 30 days you would've received the fix and shouldn't have been experiencing this issue, as mentioned [in here](https://github.com/HotCakeX/Harden-Windows-Security/issues/115#issuecomment-1722177607). Can you please confirm that you didn't do that?

The way the module/script deals with process mitigations is that first it removes all mitigations for the programs listed in the [CSV file](https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Payload/ProcessMitigations.csv), creates a clean slate, then applies the mitigations from the same CSV file on the system. That means when I removed CFG and Strict CFG, all that needs to be done is to run the Microsoft Defender category.

The reason I quickly removed all mitigations for explorer.exe was because you said there is still a problem with it and since I couldn't find the exact cause I removed all mitigations until I could be sure it works perfectly and no longer hinders productivity and usability.

I'll go ahead and restore the explorer.exe mitigations I removed.

**Comment by starraiderx** [comment]
Before opening this issue, I reran the script and rebooted my device. Maybe the way the script reapplies the mitigations is/was bugged?

**Comment by HotCakeX** [comment]
I restored the process mitigations for explorer.exe: https://github.com/HotCakeX/Harden-Windows-Security/pull/141

I tested it a lot and it does successfully remove StrictCFG from explorer.exe if it was activated.

You can verify it too:

1. Run the Microsoft Defender category
2. Use Microsoft Defender GUI -> App & Browser Control -> Exploit Protection -> Program Settings, find Explorer.exe and activate "Strict CFG" for it.
3. Run the Microsoft Defender Category again
4. If Defender GUI is open, close and reopen it, navigate to the same location and verify that the Strict CFG is no longer active.
