### ISSUE TITLE
[Bug]: Optional Windows Features > Uninstalling Notepad (system) removes Notepad from Windows Sandbox

### ISSUE THREAD

**Issue by 06b** [HotCakeX/Harden-Windows-Security#147]
### Tools category

Harden Windows Security Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

I noticed when using Windows Sandbox that when I attempted to open a .txt file, Windows suggested opening the file with Windows Media Player. This confused me for a small bit of time until I remembered that the legacy notepad had been uninstalled and my system had the modern Notepad app, which as of right now Windows Sandbox doesn't include the modern desktop apps.

Wasn't sure if this was better suited as a bug report or if should have been a discussion post. This obviously isn't a big deal as alternative notepad applications exist and can be used within Windows Sandbox.

**Comment by HotCakeX** [comment]
Hi,
That's expected since Windows Sandbox compiles its OS [on the fly](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-architecture) from the host OS files. Image files don't have a default app to be opened with in Sandbox either, so I just drop them on Edge. Windows Media Player legacy is uninstalled from the host so Sandbox is missing it even though it suggests it.

You can use VS Code web app (https://vscode.dev/) if you really need to edit text files in Windows Sandbox 🙂

**Comment by HotCakeX** [comment]
So I'm going to mark this as resolved, plz feel free to open new issues if you think there is something unexpected happening

You can either skip the optional Windows features category or after running it, navigate to Windows settings -> Apps -> Optional features and install Notepad again.

If you need more features in Windows Sandbox such as opening media files, you can also reactivate Windows Media player (legacy)

<br>

<img width="966" alt="image" src="https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/025d7f7f-f2e4-484a-aea7-0fa2c36b0cbf">

<br>
