### ISSUE TITLE
[Bug]: RemoteCertificateNameMismatch

### ISSUE THREAD

**Issue by ch0pshop** [HotCakeX/Harden-Windows-Security#190]
### Tools category

WDACConfig Module

### Does your system meet the requirements?

- [X] Yes, my system meets the requirements 👍

### Is your Windows installation genuine?

- [X] Yes, I am using genuine Windows installation. 💯

### Please explain the bug

when executing cmd from 'WDAC policy for Fully Managed device - Variant 1',   "New-WDACConfig -MakePolicyFromAuditLogs -BasePolicyType 'Allow Microsoft Base' -NoDeletedFiles"
returns error:  Invoke-WebRequest: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
![Untitled](https://github.com/HotCakeX/Harden-Windows-Security/assets/140576182/ed9b4cd0-7dfb-4ddd-9e98-81eed321b627)

**Comment by HotCakeX** [comment]
Hi,
Have you removed any built-in certificates from the system certificate stores? That error message basically means it can't find the proper certificate on your system to make a secure HTTPS connection to GitHub website to download the Microsoft recommended block rules.

**Comment by HotCakeX** [comment]
So I'm fairly certain the problem is that your certificate store is missing some of the CA certificates that come preinstalled with the OS.

You can find more info about the error in here: https://stackoverflow.com/questions/56257442/trusting-self-signed-certificate-in-invoke-webrequest-call

You can test it on an unmodified system or a clean VM.
I'll close this due to inactivity but feel free to reopen it if there is more info or create new issue if there is something else.
Thanks
