### ISSUE TITLE
Stop automatically setting UAC elevation to prompt for credentials for administrators

### ISSUE THREAD

**Issue by jxolotl** [HotCakeX/Harden-Windows-Security#2]
A malicious program may create a very similar looking interface to the UAC elevation dialog (with darken wallpaper background), clickbaiting user's password. In this case, requiring a password is less secure than no password.

Administrators should already know their passwords (or else they won't be able to login), and since Windows does GUI isolation to separate low privilege programs, this change makes little security benefit.

Baiting the password won't make a program priviledegd as Windows [filters remote UAC token](https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-security/user-account-control-and-remote-restriction#how-uac-remote-restrictions-work) (this behavior can be overriden with a registry tweak), however, leaking the password allows an attacker with physical access to the device to unlock the device.

If you insist changing this in your script, at least add a warning for this.

**Comment by HotCakeX** [comment]
Hi, what do you think about Windows security's Phishing Protection which are enabled by default?

![image](https://user-images.githubusercontent.com/118815227/213979087-9cc6f8e9-943d-4100-b746-231d3855fe4d.png)


> Enhanced Phishing Protection in Microsoft Defender SmartScreen helps protect your password from being stolen, or [phished](https://support.microsoft.com/en-us/windows/protect-yourself-from-phishing-0c7ea947-ba98-3bd9-7184-430e1f860a44), on malicious sites and apps pretending to be safe.
> 
> If you sign into Windows 11 using a password, Enhanced Phishing Protection alerts you if you type that password into a malicious website or into an application connecting to a known malicious site. Enhanced Phishing Protection helps protect your password in 3 ways:
> 
> 
> 
> If you type your Microsoft account password into a site that SmartScreen finds malicious, Enhanced Phishing Protection will alert you. It will also prompt you to change your password so attackers can't gain access to your account.
> 
> Reusing the same password makes it easy for attackers who compromise your password to gain access to your other accounts. Enhanced Phishing Protection can warn you if you reuse your Microsoft account password on other sites or apps and prompt you to change your password.

> Since it's unsafe to store your password in text editors, Enhanced Phishing Protection can warn you if you type your password into Notepad or a Microsoft 365 Office application like Word or OneNote.

> 

[More in here](https://support.microsoft.com/en-us/topic/protect-your-microsoft-password-from-being-phished-e4e8e611-e4b3-4be9-914c-db1657c337cf)

Even if all other security measures fail to detect such a phishing malicious program that tries to capture user's password, Windows security's Phishing Protection will warn user about entering their passwords into 3rd party apps. I've tested it too.

also, about physical security, the script enforces Startup PIN and full drive encryption, allowing only 6 wrong PINs to be entered before TPM locks the entire system where only 48-digit backup code can be used to unlock it; using passwords alone doesn't provide access.

it's highly recommended for users to use Windows Hello authentication. in addition to that, making Microsoft account password-less in order to enforce multi-factor authentication with the authenticator app, which is impossible to bypass even withy MFA fatigue technique.

the reason I decided to enforce [secure desktop prompt](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-switch-to-the-secure-desktop-when-prompting-for-elevation#reference) for credentials instead of a simple prompt was to constantly verify the user and their access, something like a zero-trust scenario.

**Comment by jxolotl** [comment]
> what do you think about Windows security's Phishing Protection which are enabled by default?

To be honest I haven't explored it in deep because I don't even know it actually protects against arbitrary programs, I've always thought it's for web browsers and that it's just a settings frontend for Microsoft Edge. I will play around it later, once I have free time.

The only problem is that, whether it's a universal protection against all sort of password click baiting (with proper [threat model](https://en.wikipedia.org/wiki/Threat_model)) or if it's just a reputation-based protection that's part of SmartScreen, because the latter would definitely fail, given enough time, as malicious program creator usually repeats rotating their codes until it passes SmartScreen.

> but it is hypothetical, and we can't be constantly afraid of that specific hypothetical scenario and be always scared to enter our own passwords

Other than the click baiting issue, there's another obvious problem with this approach (I'm not to say it's a downgrade security-wise, but if this is for home users then it'll probably cause more harm)

Frequently asking for password is not a good security design social-engineering-wise, it makes users fatigue and less vigilance when a password prompt is shown, a UAC prompt showing up 100 times a day won't make the system any more secure if users are just going to blindly type their passwords without actually reading anything. There's a sentence "If you highlight everything, you're highlighting nothing". A password prompt shown being always related to something important makes users more conservative at whether to give out their passwords. Windows default settings excels at this, as the UAC only asks for consent when a non-Microsoft binary asks for elevation.

Making UAC more paranoid can be useful, but only when users know what they're doing, otherwise it's only going to become yet another annoyance to turn off, hence why I'm asking that, if you insist setting password prompt, at least warn users about it, as this can potentially make the system less secure.

> the script enforces Startup PIN and full drive encryption

Just FYI, given that physical attack is also taken into consideration, also make sure secure boot is configured properly, preferably allowing only Microsoft Windows to boot (I think some [newer devices](https://www.tomshardware.com/news/security-measure-forces-windows-on-lenovo-laptops) do this by default, and this actually caused some flames in Linux community, Microsoft evil balabala), shim/grub is known [to](https://askubuntu.com/questions/1247826/secure-boot-verification-of-initramfs) . [be](https://askubuntu.com/questions/1333936/why-does-shim-mokmanager-allow-to-circumvent-all-protections-of-secureboot-an) . [problematic](https://security.stackexchange.com/questions/255691/how-to-prevent-grub-cfg-from-breaking-the-chain-of-trust) at securing boot chain, their implementation is only as useful as allowing Linux desktop to boot while enabling secure boot, but not necessarily hardening security by taking advantage of TPM / hardware root of trust.

Allowing shim/grub to boot doesn't circumvent BitLocker as long as TPM PCR is in place, however, it does open the gaps to execute arbitrary programs before Windows, even though they can't break the integrity of Windows without alerting users (BitLocker changes to ask for recovery password if that happens).

Guaranteeing Microsoft Windows being the only allowed OS can be difficult to achieve with a script as it's a firmware settings, so perhaps you can add some documentations to guide users into toggling secure boot and allowing only Microsoft Windows.

**Comment by HotCakeX** [comment]
> To be honest I haven't explored it in deep because I don't even know it actually protects against arbitrary programs, I've always thought it's for web browsers and that it's just a settings frontend for Microsoft Edge. I will play around it later, once I have free time.
> 
> The only problem is that, whether it's a proper security mechanism against all sort of password click baiting (with proper [threat model](https://en.wikipedia.org/wiki/Threat_model)) or if it's just a reputation-based protection that's part of SmartScreen, because the latter would definitely fail, given enough time, as malicious program creator usually repeats rotating their codes until it passes SmartScreen.
> 

Of course, take your time,
it warns when I enter my password even in Notepad which is a trusted app:


![test1](https://user-images.githubusercontent.com/118815227/214019223-e6ae022d-ca49-4bfc-bcb4-0dc6d2c9547f.png)

in my experience, the latest and most strict but also accurate security feature is Smart App Control, a malicious program first convincing user to download it, bypass SmartScreen and essentially bypassing all other security layers, would be stopped by Smart App Control if it's not signed and not verified by [ISG](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-with-intelligent-security-graph).

Smart App Control doesn't just require a digital signature, it requires a verifiable and reputable one. I tested it by creating a self-signed certificate, signed an executable that was getting blocked by Smart App Control, even made Windows trust my certificate by installing it in Trusted root CAs store, still was blocked.

<br>

> Other than the click baiting issue, there's another obvious problem with this approach (I'm not to say it's a downgrade security-wise, but if this is for home users then it'll probably cause more harm)
> 
> Frequently asking for password is not a good security design social-engineering-wise, it makes users fatigue and less vigilance when a password prompt is shown, a UAC prompt showing up 100 times a day won't make the system any more secure if users are just going to blindly type their passwords without actually reading anything. There's a sentence "If you highlight everything, you're highlighting nothing". A password prompt shown being always related to something important makes users more conservative at whether to give out their passwords. Windows default settings excels at this, as the UAC only asks for consent when a non-Microsoft binary asks for elevation.
> 
> Making UAC more paranoid can be useful, but only when users know what they're doing, otherwise it's only going to become yet another annoyance to turn off, hence why I'm asking that, if you insist setting password prompt, at least warn users about it, as this can potentially make the system less secure.

<br>

I agree with you, I've felt that too, but instead of showing yet another warning, I think it'd be better to choose an optimal default for the script. for example, I think you'll approve If I change the `ConsentPromptBehaviorAdmin` from `prompting for credentials on secure desktop` to `prompt for accept/deny on secure desktop`, and also label it with `#TopSecurity` to let users/readers know there is a security feature that can be used to harden Windows even further if they wish to do so but comes with inconvenience. and that'll make the total `#TopSecurity` tagged commands to 4.


<br>

> 
> Just FYI, given that physical attack is also taken into consideration, also make sure secure boot is configured properly, preferably allowing only Microsoft Windows to boot (I think some [newer devices](https://www.tomshardware.com/news/security-measure-forces-windows-on-lenovo-laptops) do this by default, and this actually caused some flames in Linux community, Microsoft evil balabala), shim/grub is known [to](https://askubuntu.com/questions/1247826/secure-boot-verification-of-initramfs) . [be](https://askubuntu.com/questions/1333936/why-does-shim-mokmanager-allow-to-circumvent-all-protections-of-secureboot-an) . [problematic](https://security.stackexchange.com/questions/255691/how-to-prevent-grub-cfg-from-breaking-the-chain-of-trust) at securing boot chain, their implementation is only as useful as allowing Linux desktop to boot while enabling secure boot, but not necessarily hardening security by taking advantage of TPM / hardware root of trust.
> 
> Allowing shim/grub to boot doesn't circumvent BitLocker as long as TPM PCR is in place, however, it does open the gaps to execute arbitrary programs before Windows, even though they can't break the integrity of Windows without alerting users (BitLocker changes to ask for recovery password if that happens).


<br>


That's true, the SecureBoot enabled only through Group policy/Registry isn't by itself as strong as the one enabled in UEFI firmware. 
Thank you for that 🙏 since I set it up on my UEFI settings years ago kinda thought it'd be the same on everyone else's computer!


> 
> Guaranteeing Microsoft Windows being the only allowed OS can be difficult to achieve with a script as it's a firmware settings, so perhaps you can add some documentations to guide users into toggling secure boot and allowing only Microsoft Windows.


I will definitely collect guides and resources for it and will make it clear that those firmware settings need to be set so that the script can secure the OS the way it claims.

**Comment by jxolotl** [comment]
Phishing protection seems to not detect my Windows Hello PIN, but it does detect my password in some apps, however not all of them ([Notepads](https://apps.microsoft.com/store/detail/notepads-app/9NHL4NSC67WM) to name one). I'll definitely experiment with it more later. Does Windows have anything similar to Android's Lockdown? where all biometric unlock (Windows Hello equivalent) is disabled and you're forced to use password to login. I know you can replicate similar mechanism with login attempt threshold and BitLocker Startup PIN but is there any more user-friendly version?

>  for example, I think you'll approve If I change the ...

Yes, I agree it's a better optimal default.

**Comment by jxolotl** [comment]
I haven't used Smart App Control because I turned off optional diagnostic data right after I reinstalled Windows 11, not knowing that diagnostic data is required for SAC. But I also feel like SAC is still unfinished as you can't manually whitelist certain programs, so you're forced to live with it when it gets in the way, or permanently disable it.

What's up with Windows AppContainer technology lately (I came from other OS)? [UWP is deprecated](https://www.thurrott.com/dev/258377/microsoft-officially-deprecates-uwp#:~:text=Microsoft%20continues%20to%20baby%2Dstep,future%20of%20Windows%20application%20development.) in favor of Windows Apps SDK, and PartialTrust for Win32 in MSIX is [largely](https://github.com/microsoft/WindowsAppSDK/issues/219) [undocumented](https://github.com/microsoft/WindowsAppSDK/discussions/410) [and](https://github.com/microsoft/WindowsAppSDK/discussions/1900) [unsupported](https://github.com/microsoft/microsoft-ui-xaml/issues/7982). There's only this page which states [Windows 11 will run Win32 apps in containers](https://www.gearrice.com/update/windows-11-will-run-win32-apps-in-containers/) with only a twitter link which sounds just like exaggerated fake news.

Windows Sandbox still doesn't allow multiple instancing, making it useless for software compartment. Sandboxed / containerized application isn't the ultimate way to achieve security but it's a important factor to restrict what an app can do.

**Comment by HotCakeX** [comment]
> Phishing protection seems to not detect my Windows Hello PIN, but it does detect my password in some apps, however not all of them ([Notepads](https://apps.microsoft.com/store/detail/notepads-app/9NHL4NSC67WM) to name one). I'll definitely experiment with it more later. 

Yes that only works with passwords, the mitigation is to prevent theft of passwords that can be used elsewhere, but since PINs are local and only for a single user account, they're not in the scope.


> Does Windows have anything similar to Android's Lockdown? where all biometric unlock (Windows Hello equivalent) is disabled and you're forced to use password to login. I know you can replicate similar mechanism with login attempt threshold and BitLocker Startup PIN but is there any more user-friendly version?
> > 
> 

I don't think so, there is an exact opposite option though

[Why a PIN is better than an online password](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)

![image](https://user-images.githubusercontent.com/118815227/214032059-8f866321-13fa-47e0-b762-2c13b76d8d70.png)


I do use Android but never tried that feature. found [this](https://screenrant.com/android-lockdown-mode-purpose-enable-how-explained/):

> Whichever advanced [unlocking](https://support.google.com/pixelphone/answer/6093922) may be used, there could be circumstances when the user would want to prevent quick and easy unlocking of their smartphone. Google added a solution to Android called ‘Lockdown mode.’ Once enabled, notifications will be turned off, preventing any lock screen notifications even if they are switched on elsewhere. Fingerprint and face recognition will also be disabled as a way to [unlock the device](https://screenrant.com/android-iphone-passcodes-not-protected-fifth-amendment-court-ruling/). This means the user’s biometric data can’t be used to unlock the phone against their will. Other types of smart unlocking such as by location, Bluetooth devices, or other advanced methods are also disabled. This leaves only one way of unlocking the phone, by entering the correct PIN code, password or pattern.


I don't know what Google was thinking but I can't imagine a scenario where it can be really useful. maybe one scenario, user is unconscious or asleep? Idk

but if it's being used as a security measure for when user is fully awake, it probably won't stop whoever trying to coerce user to unlock the phone, they can use threats, torture etc. and force user do it for them.

**Comment by HotCakeX** [comment]
@jxolotl I've made the necessary changes in here, you can review it
 https://github.com/HotCakeX/Harden-Windows-Security/pull/3

**Comment by HotCakeX** [comment]
> I haven't used Smart App Control because I turned off optional diagnostic data right after I reinstalled Windows 11, not knowing that diagnostic data is required for SAC. But I also feel like SAC is still unfinished as you can't manually whitelist certain programs, so you're forced to live with it when it gets in the way, or permanently disable it.

I think there is a 50-50 chance that we will get the ability to whitelist programs in Smart App Control or have the same exclusion rules for Windows Defender to apply to Smart App Control too.

I don't think I'd want it to have the whitelist option become available though. because it's supposed to be smart and uses AI, like its description says, its decisions change based on data it receives and analyzes.
it's exactly the same as WDAC. with WDAC, you have to create your own policy but Smart App Control uses its own specialized policy. I think users will most likely compromise themselves by turning it off for some random app they download from the Internet. other OSes have such tight measures so why shouldn't Windows have it? other OSes enforce digital signature on apps that can run on their ecosystem, I think it's time developers adapt to the new secure Windows ecosystem as well and don't try to circumvent it. that's my opinion..

> 
> What's up with Windows AppContainer technology lately (I came from other OS)? [UWP is deprecated](https://www.thurrott.com/dev/258377/microsoft-officially-deprecates-uwp#:~:text=Microsoft%20continues%20to%20baby%2Dstep,future%20of%20Windows%20application%20development.) in favor of Windows Apps SDK, and PartialTrust for Win32 in MSIX is [largely](https://github.com/microsoft/WindowsAppSDK/issues/219) [undocumented](https://github.com/microsoft/WindowsAppSDK/discussions/410) [and](https://github.com/microsoft/WindowsAppSDK/discussions/1900) [unsupported](https://github.com/microsoft/microsoft-ui-xaml/issues/7982). There's only this page which states [Windows 11 will run Win32 apps in containers](https://www.gearrice.com/update/windows-11-will-run-win32-apps-in-containers/) with only a twitter link which sounds just like exaggerated fake news.
> 

I'm not quite sure about that. there are apps that run in AppContainer sandboxes at the moment but not all Win32 programs that are downloaded from store do that. from what I've read each app developer can choose how their apps run?

> Windows Sandbox still doesn't allow multiple instancing, making it useless for software compartment. Sandboxed / containerized application isn't the ultimate way to achieve security but it's an important factor to restrict what an app can do.

I do my software compartmentation using Hyper-V VM, it's perfect, not even exaggerating, I have old test PC/server from years ago with Intel 7th gen CPU. Hyper-V VMs with Windows 11 latest version run with native performance on it, while at the same time Android subsystem is running in the background and host is doing a bunch of stuff.

good thing is that Hyper-V VM when saved in a drive other than `C` can survive a clean OS install or migrate to other machines, Windows Sandbox wouldn't do that even if it was persistent or multi-instanced.

Windows Sandbox is the environment where you run untrusted software or open untrusted website and destroy that OS in a second once you're done.
