### ISSUE TITLE
[Bug]: Issue with Docker Desktop on enabling Dangerous Script Blocking

### ISSUE THREAD

**Issue by tEctutoRIt** [HotCakeX/Harden-Windows-Security#303]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

When using the latest version of Docker Desktop, it is unable to start because of the inability to access cscript, which is blocked by Dangerous Scripts Blocking WADC. This might be an issue for a lot of people, and I don't being a tech expert, do not know how to unblock specifically the Docker app.

### Error Details

```console
In Event Viewer, Code Integrity Operational Events shows:

Code Integrity determined that a process (\Device\HarddiskVolume6\Program Files\Docker\Docker\frontend\Docker Desktop.exe) attempted to load \Device\HarddiskVolume6\Windows\System32\cscript.exe that did not meet the Enterprise signing level requirements or violated code integrity policy (Policy ID:{9f0581b7-7e1d-4fdd-8d33-6dbe847d3130}).
```

**Comment by HotCakeX** [comment]
Hi,
This isn't a bug, as mentioned [in the release notes here](https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.4.6), 3rd party apps might attempt to use these insecure script hosts and I explained that [you can easily remove them if you need to](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Harden%E2%80%90Windows%E2%80%90Security%E2%80%90Module#unprotect-windowssecurity-cmdlet).  That is also why it's an optional sub-categories of the main category.

So the intention **is** blocking them from being used and that's the expected behavior, but if you want to allow them to be used then you can simply remove them.
