### ISSUE TITLE
[Bug]: Edit-WDACConfig -AllowNewApps ==> blocked by WDAC

### ISSUE THREAD

**Issue by Kofl** [HotCakeX/Harden-Windows-Security#327]
### Tools category

WDACConfig Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

```
Edit-WDACConfig -AllowNewApps -SuppPolicyName 'TreeSize' -PolicyPath "C:\wdac\Base Policy Enforce Mode_2024-07-23_v10.0.3.6.xml"
Audit mode deployed, start installing/running your programs now
```

Starting the application => blocked by WDAC

Windows 11 24H2, en-gb

Happy to provide further requested information

**Comment by HotCakeX** [comment]
Do you have more than 1 non-system base policy deployed on the system that is in charge of blocking files?

**Comment by HotCakeX** [comment]
You can enter this command
```powershell
ConvertTo-WDACPolicy
```
or this for full details
```powershell
ConvertTo-WDACPolicy -ExtremeVisibility
```
or check the event logs, that will show you which policy is blocking the files. The behavior you're describing usually originates from having more than 1 base policy. The module turns on audit mode in the policy you select, but if there are more than 1 (which isn't necessary), then the other one will still be enforcing and blocking files. If this is the case, we can convert this issue into a discussion to come up with a solution for your case.

**Comment by Kofl** [comment]
Thanks for the feedback, so far its only one base policy visible via 

`Confirm-WDACConfig -ListActivePolicies -OnlyBasePolicies`

and seems to be blocked by that one?

![image](https://github.com/user-attachments/assets/8fb57dad-9374-4bd6-b9e4-814db2aaf5c4)

**Comment by HotCakeX** [comment]
Interesting, when you run this command in a new terminal tab, after the audit mode has been turned on
```powershell
Confirm-WDACConfig -VerifyWDACStatus
```
do you see number 2 for both of the items?

**Comment by Kofl** [comment]
yes

![image](https://github.com/user-attachments/assets/f29567ca-fc62-4755-9601-d0d3adaa52cb)

**Comment by HotCakeX** [comment]
Is Smart App control enabled on your system? Have you used Intune to deploy one of the App control presets? You can run this for system policies:
```powershell
Confirm-WDACConfig -ListActivePolicies -OnlySystemPolicies
```
I'm not sure if this is a bug in the module, I haven't been able to reproduce it so far. If you can try a clean VM, deploy a base policy, then use the `Edit-WDACConfig` command to turn on audit mode in it to install an app, that's what I did just now in a Hyper-V VM and it works fine like before.

**Comment by Kofl** [comment]
Smart App Control is set to Evaluation

Not aware of any App control presets set via Intune, WDAC policies are deployed via Intune.

Would that look okay and should not cause the issue?

![image](https://github.com/user-attachments/assets/4359389c-db9f-4913-a1ff-daa79b273f1f)

![image](https://github.com/user-attachments/assets/ab030471-bdf5-42e8-a83a-6d06205d0968)

Could I use WDACConfig to deploy our/the same base policy on the clean VM as now via Intune?

**Comment by HotCakeX** [comment]
You don't need the WDACConfig module for deploying a XML file you have on the local system, you can use these commands
```powershell
ConvertFrom-CIPolicy -XmlFilePath basepolicy.xml -BinaryFilePath basepolicy.cip
CiTool.exe --update-policy basepolicy.cip
```

But now that you mentioned you deployed them originally from the Intune, i'm thinking maybe Intune agent (running as SYSTEM) is preventing the module (running as Admin) to modify the deployed policy, or maybe Intune is actively restoring the system back to the state you set in Intune portal via config refresh or something similar.

I haven't done many tests to modify policies deployed via Intune locally using the `Edit-WDACConfig` cmdlets, for Intune scenario I've developed and considered other ways, and all of them involve creating the policy locally and then deploying them via Intune itself, because the Intune managed systems are usually too many to be managed locally and individually.

**Comment by HotCakeX** [comment]
If you want i can include logic to manage Intune deployed policies as well, but it will be through the Microsoft Graph and not locally.

Due to the idempotency nature of the Intune, it reapplies the same WDAC policies you deploy through the portal over and over again on the system, there is no way to override it locally.
