### ISSUE TITLE
[Bug]: New update removes all existing controlled folder allowances

### ISSUE THREAD

**Issue by tEctutoRIt** [HotCakeX/Harden-Windows-Security#342]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

After updating to latest version and applying Microsoft Defender category leads to removal of all existing control folder exclusion except two and adds new weird exploit mitigations compared to earlier. I have attached xml of it.
[Settings.zip](https://github.com/user-attachments/files/17001842/Settings.zip)

**Comment by HotCakeX** [comment]
What is "weird" exactly? Can you be more specific?

**Comment by HotCakeX** [comment]
> I have uploaded settings.xml in zip to show you that. eg, ASLR ForceRelocateImages="false" for b2sum.exe, arch.exe, ahost.exe,... I didn't do these, and they were not there before last update so...

Those are added because they are Git executables. Git executables, whether inside of Git standalone package or part of GitHub desktop, are not compatible with the mandatory ASLR, that is why the Microsoft Defender category adds them to the exclusions.

It's explained on the readme in the [Microsoft Defender category](https://github.com/HotCakeX/Harden-Windows-Security?tab=readme-ov-file#microsoft-defender). That change was documented in the release notes. It was also a feature request made by a user.

* https://github.com/HotCakeX/Harden-Windows-Security/wiki/Git-GitHub-Desktop-and-Mandatory-ASLR
* https://github.com/HotCakeX/Harden-Windows-Security/issues/266
* https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.4.6

<br>

**Comment by HotCakeX** [comment]
It shouldn't do that but if it does i'm sorry, i'll look into it and fix it in the upcoming update.

**Comment by HotCakeX** [comment]
@tEctutoRIt I fixed the issue with Controlled Folder Access exclusions clearing. Thanks for reporting it!
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.6.2
