### ISSUE TITLE
[Suggestion]: Hardening SSH

### ISSUE THREAD

**Issue by agpt8** [HotCakeX/Harden-Windows-Security#354]
### Are you sure the Security measure is not already implemented?

- [X] Yes, I have checked and the Security measure I'm suggesting to be implemented is not duplicate. 🫡

### Please explain your new Security measure suggestion

The current windows versions include openssh v9.x and openssh server is available as an optional feature in the settings app. By default, SSH is secure but can be hardened much more. Atleast in terms of what ciphers, algorithms and CA's it uses. This is based on this repo: https://github.com/JuliusBairaktaris/Harden-Windows-SSH, the script there is simple and configures user's and system's ssh to use much stronger algorithms, cipher's and CA's. Beta installation of OpenSSH is not needed.

The above-mentioned repo is again an inspiration from SSH Audit's repo: https://github.com/jtesta/ssh-audit/wiki/Windows-11, which contains many more platforms which can be hardened in a similar way. The config given on this one varies slightly and is a little looser than the first repo mentioned above. We can decide which should be included _(personally I use a combination of the two along with some of my own changes)_.

Another good read for this is this answer on stack exchange: https://security.stackexchange.com/questions/257670/ssh-server-configuration-best-practices/257678#257678

To check the default state of security for ssh:
1. Go to https://sshaudit.com
2. Click on the button Begin Client Audit. Three new buttons will appear.
3. Click on the middle one that says Copy OpenSSH client command
4. Open terminal, paste the command and hit Enter
5. The connection will close, and the scores will be displayed on the site in a few seconds along with the reasoning for the given score.

**Comment by HotCakeX** [comment]
Hi, 
Thanks for the suggestion, i looked into it, this is the line i'm going to add to the SSH client config in user directory (with proper checks to make sure it's not added if it already exists), it will be part of the Non-Admin category since it doesn't need Admin privileges and is tied to each user.

```
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
```

Excluding anything that falls under the FUD category mentioned in that website, that solves the issue with weak MACs (Message Authentication Codes). 

By the way Post-quantum cipher suites are on the way from NIST for Windows, TLS, SSH etc. 
https://techcommunity.microsoft.com/t5/security-compliance-and-identity/microsoft-s-quantum-resistant-cryptography-is-here/ba-p/4238780

**Comment by HotCakeX** [comment]
@JuliusBairaktaris 
I checked that because it was mentioned in the OP. I really suggest not promoting or using that sshaudit website because it spreads false information and conspiracy theories with 0 logical proof, makes it unreliable. I would highly doubt the intentions of anyone who would say such things.

Many of NIST's standards have been widely reviewed and implemented by the international cryptographic community. If there were backdoors or inherent weaknesses intentionally inserted into them, it is likely that they would have been discovered by now through independent cryptanalysis or we would have hard proof against them.
