### ISSUE TITLE
[Suggestion]: Adding additional algorithms to TLS

### ISSUE THREAD

**Issue by agpt8** [HotCakeX/Harden-Windows-Security#360]
### Are you sure the Security measure is not already implemented?

- [X] Yes, I have checked and the Security measure I'm suggesting to be implemented is not duplicate. 🫡

### Please explain your new Security measure suggestion

This is the order that the module sets for TLS ECC curves:
nistP521
curve25519
NistP384
NistP256

A [discussion](https://github.com/HotCakeX/Harden-Windows-Security/commit/5b5be1fcab8f7bf5d364f48459aecfc54c6eff9d#commitcomment-115982586) is also linked in the README, detailing why this order was used.

I think we can add more curves to this list.
Currently, windows support a decent number of curves (run `certutil.exe –displayEccCurve` to see the entire list). 
Here is the order that I am proposing:

brainpoolP521t1   ---> twisted curve, better performance
brainpoolP521r1   ---> random curve
nistP521
curve25519
brainpoolP384t1
brianpoolP384r1
NistP384
brainpoolP256t1
brainpoolP256r1
NistP256
secP256k1

There are reports about secP256r1 and others similar ones having backdoored by NSA. There are also reports about nist ones on this list having backdoored but I wouldnt read too much between the lines.

secP521r1 is a NIST curve and is very similar to nistP521. This and other curves can be added to the list as well at appropriate places. sec curves are widely used but the alternatives listed above works just as well.

**Comment by HotCakeX** [comment]
We can reopen this when there is more info to work with because at this state i can't do anything about it and I already explained about the NSA talk [in here](https://github.com/HotCakeX/Harden-Windows-Security/issues/354#issuecomment-2411997902) and it's not a factor when deciding which cipher or curve to use.

Realistically, i think the actual security benefit will come when we use [post quantum cryptography](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/microsoft-s-quantum-resistant-cryptography-is-here/ba-p/4238780) which is available in [SymCrypt](https://github.com/microsoft/SymCrypt) and soon in CNG, Schannel, SSH etc.
