### ISSUE TITLE
Issue with Memory Integrity Re-activation

### ISSUE THREAD

**Issue by starraiderx** [HotCakeX/Harden-Windows-Security#39]
Firstly, I'd like to express my appreciation for the effort put into the Harden Windows Security repository. 

However, I have encountered a problem while trying to use the script provided in the repository.

The issue pertains to the Memory Integrity feature. After going into the Group Policies and Registry Editor, I successfully disabled the corresponding entries for Memory Integrity, effectively removing its management by the administrator.

However, the problem arises when I attempt to switch off Memory Integrity. Despite successfully disabling it and restarting the system, Memory Integrity seems to reactivate itself.

I am unsure as to why this is happening and would appreciate any assistance in resolving this issue.

Thank you for your time and support.

**Comment by Harvester57** [comment]
Did you by anyc chance enable the policy with the UEFI lock ?

If yes, you need to perform additional steps to entirely disable the memory integrity security function, as described here: https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disabling-windows-defender-credential-guard-with-uefi-lock

**Comment by starraiderx** [comment]
Thank you for your response, @Harvester57. In retrospect, I realize I should have been more clear about the registry values and group policies I altered. My apologies for the omission.

I made modifications to the following:

    Under Computer Configuration > Administrative Templates > System > Device Guard, I set the 'Turn on Virtualization Based Security' to off.
    Additionally, I changed the registry value HKLM > SYSTEM > CurrentControlSet > Control > DeviceGuard > Scenarios > CredentialGuard to 0.

I am implementing the script on a fresh Windows installation.

From my understanding, the steps you mentioned should have been addressed when I edited the group policy. I would appreciate any further insight you might have into why Memory Integrity is still reactivating itself.

**Comment by HotCakeX** [comment]
Thank you @Harvester57 for helping ^^

@starraiderx Sorry for the delay, please refer to this official doc:

https://learn.microsoft.com/en-us/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity#enable-memory-integrity-using-group-policy

> Select Enabled and under Virtualization Based Protection of Code Integrity, select Enabled without UEFI lock. Only select Enabled with UEFI lock if you want to prevent memory integrity from being disabled remotely or by policy update. Once enabled with UEFI lock, you must have access to the UEFI BIOS menu to turn off Secure Boot if you want to turn off memory integrity.

TL;TR : You need to go to UEFI settings and turn off Secure Boot.

P.S the entire point of using UEFI Lock is to prevent this exact situation, to prevent security features such as Memory Integrity from turning off by Registry or Group Policy manipulation, but since you have physical access to your device, know the UEFI password and you're the device owner, you can turn it off. 🙂

**Comment by starraiderx** [comment]
Solved! Than you so much!

**Comment by HotCakeX** [comment]
> Solved! Thank you so much!

You're welcome ^^
