### ISSUE TITLE
[Bug]: Scroll bars stop working in System Information

### ISSUE THREAD

**Issue by WildByDesign** [HotCakeX/Harden-Windows-Security#415]
### Tools category

AppControl Manager app

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

In the System Information section, the scroll bars (both vertical and horizontal) stop working very frequently.

The scroll bars wont appear again unless you hover the cursor over a policy or header in the list view.

So if you have a full list view of policies, you likely will never see this issue. But if you have less policies so that there is some blank space in the list view, this issue happens all the time.

The animated gif below captures the bottom scroll bar disappearing. But I have also reproduced it with the vertical one as well. The animation captured my mouse movements but it didn't capture my mouse clicks. I likely didn't have that setting enabled in Screentogif app. However, I was clicking the mouse in the area of the missing scroll bar as well when hovering over it.

![Animation](https://github.com/user-attachments/assets/04e59cc2-dad4-4efc-b3b4-b0d544ac0802)

**Comment by HotCakeX** [comment]
Hi,
When the scrollbar disappears you just move the mouse over the data and it will appear again like it's doing in the gif.

Mouse scroll wheel, trackpads on laptops and touch works too for horizontal and vertical scrolling, without the need to even see the scrollbars.

What you're seeing is the normal behavior of the DataGrid. in the future it will be replaced with a more modern element but that's not ready yet from community toolkits. Though I'll tweak it a little bit in version 1.5.0.0 to try to improve it.

Also looks like you're in a VM with no GPU, maybe that's affecting its behavior too.

**Comment by WildByDesign** [comment]
Sorry, it looks like I was wrong about that animation effects thing. Even with the animation effects on, the scroll bar still dies. It just takes an extra 1-2 seconds to die because of the delay of the animation.

I think that the only way that I can effectively work with this right now (workaround) is to make the AppControl Manager window really small and also populate the system policies as well so that the entire grid is full.

**Comment by HotCakeX** [comment]
I have a suggestion, you said you prefer to disable animations in Windows which is understandable, but when you do that, what if you enable "always show scrollbars"? that will fix the problem.

![image](https://github.com/user-attachments/assets/4df3bf3b-85cb-43e1-8ff8-53526f302b00)

Like you said i disabled animations and i could reproduce this problem but always showing scrollbars prevents them from disappearing.

I might have better solutions/workarounds in the future but i won't be able to fix this in the code because of the reasons i mentioned above.

**Comment by WildByDesign** [comment]
> To fix this problem I'd need to re-implement the entire scrollbar and scrollviewer by collecting all the relevant code from that source, find the part responsible for this issue and fix it.

This sounds like it could be a lot of work for you. It is definitely strange that they deprecated the data grid without the new one being ready. If the other one is, say, 6-12 months away, I would just wait. I don't want you to waste your time on this unless more people end up reporting it.

> I have a suggestion, you said you prefer to disable animations in Windows which is understandable, but when you do that, what if you enable "always show scrollbars"? that will fix the problem.

Yay! Thank you, Violet. I didn't even realize that was an option. Not only does this work perfectly, but I actually quite like it. I'm glad you found this option.

So I am happy with this. I would say it's completely up to you if you want to keep this issue open or close it. I'm good either way. I'll let you decide on that. Cheers!

**Comment by HotCakeX** [comment]
@WildByDesign I think the new DataTable will have more features than it currently has in 12 months.
I agree, it'd take lots of my time to salvage the original DataGrid, the repo has 200 filed issues, many related to DataGrid and last commit was 3 years ago for it. It has other problems too related to trimming. I can use the time to finish up AppControl manager and move to other roadmap items, though if someone else wants to contribute and make a PR to fix it that's always welcome.

I'm glad you're happy with the workaround, i had more ideas to automate it, for example i can detect when animations are off in Windows settings, but i can't make the app think the "always show scrollbars" option is enabled because [it's a read-only property](https://learn.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings.autohidescrollbars?view=winrt-26100), so when someone disables animations, i could show some sort of notice in the app settings => Appearance (user would have to navigate to there to see it so it own't be distracting) to suggest turning on "always show scrollbars" option for better experience in DataGrids, it could have a small button that links to this issue as the reason for the suggestion.


Yes i think we can close this for now but feel free to reopen or make new ones if something else comes up. Thank you

**Comment by HotCakeX** [comment]
This is how the notice will look like. It changes in real time, if you modify Windows Settings, it will instantly appear/disappear.

![image](https://github.com/user-attachments/assets/3768de2e-f56a-40d8-82ac-fbb272d7a826)

**Comment by WildByDesign** [comment]
> This is how the notice will look like. It changes in real time, if you modify Windows Settings, it will instantly appear/disappear.

That looks good and should be sufficient for now.

I am still experiencing the dead scroll bar sometimes even with animations enabled, just not as often.

When I woke up this morning, I thought of a possible workaround that might be even better.

Since I am not a programmer, my terminology might be wrong so please bear with me. The bottom part of your DataGrid (vertical) seems to be set to a static size. My suggestion would be to have the vertical measurement of the DataGrid area set to automatically resize according to the DataGrid information that has populated.

You would want to set a maximum vertical size though which would likely be set to what you have now.

If a user populates a list of policies that is less than the maximum vertical size, the outer area of the DataGrid would shrink to the bottom of the populated DataGrid policy info.

This would resolve the issue more properly because the user would be guaranteed to hover the cursor over a line in the DataGrid which would then instantly bring back the scroll bar.

I hope this makes sense. If necessary, I could create a mock-up image or something.

Anyway, let me know what you think.

**Comment by WildByDesign** [comment]
I forgot to mention something. I don’t think that this will need to be done for the horizontal measurement though because the horizontal DataGrid info will always overflow the area anyway which is perfectly fine.

**Comment by HotCakeX** [comment]
When i set the DataGrid's height to auto instead of dedicating the remaining area to it, it malfunctions when the count of the data varies (e.g, sometimes there are 2 policies, and then you check the box for system policies and after refresh 10 more will be added), it gets stuck.

The scrollbars never disappear on me when animations are on, though there are so much room for improvement when it comes to scrolling DataGrid in general.

**Comment by HotCakeX** [comment]
I completely took care of this problem
https://github.com/HotCakeX/Harden-Windows-Security/pull/608

Will be available in AppControl Manager v1.9.1.0

**Comment by WildByDesign** [comment]
Wow that is a monster-sized commit. Thank you so much for following up on this issue. I look forward to trying that new release as soon as it's ready. Cheers! 💯
