### ISSUE TITLE
New suggestions for the project

### ISSUE THREAD

**Issue by dennyamarojr** [HotCakeX/Harden-Windows-Security#45]
**Have you completely read everything and made sure the Security measure you are suggesting hasn't already been implemented?**
Yes.

Hi @HotCakeX , 

I have some suggestions for the project as the title says, I was running the script and unfortunately, I got a Inacessible_BOOT_DEVICE error, and I think I discover the problem. Since I start to use Kaspersky Plus, has a possibility of Kaspersky block some powershell scripts and cause the issue. Here's a screenshot
![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/36896116/cef896bc-05e7-44ee-97c9-7a9ebdef2586)

Maybe some warning, like we have for Battle.net will be useful for the users.

Other suggestion is warn the users about Smart App Control since this feature is controlled by Microsoft and I think that only azure members could configure the smart app control policy template, some users could have some issues while running the programs or games. The alternative recommendation is use WDAC, which users has totally control of the whitelist and blocklist of apps.

But if users want to use Smart App Control and they have some issues, here's a workaround I found
1 - Go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy and change VerifiedAndReputablePolicyState to desired state:
Enabled - 1
Evaluation Mode - 2
Off - 0

You will notice that in the following regedit key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Protected
VerifiedAndReputablePolicyStateMinValueSeen is set to 1, which mean is Enabled, don't touch in this.

2 - After change the state of Smart App Control, you can use the programs and games that was having some issues with Smart App Control, when you finish to use the programs, games make sure to navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy and change VerifiedAndReputablePolicyState to 1 again.

WARNING: Do not restart the computer before restoring the state of VerifiedAndReputablePolicyState to 1 which is Enabled, if you restart your computer after change the state and not restore to Enabled, Smart App Control will be permanently disabled.

**Comment by HotCakeX** [comment]
Hi,
Using 3rd party AV is neither needed nor supported by the script since it activates all of the Microsoft Defender features and heavily relies on it. The screenshot and issue you are having is not related to the script. it must be obvious when user reads the Readme that Microsoft Defender and all the features the script activates is more than any other 3rd party AV solution.

Everything in the Readme is equally Important, I already inform users to read the Readme at the beginning of the script when they run it.

About Smart App Control, manual registry modification is neither recommended nor needed, all users have to do in order to activate or deactivate it is to use the toggle in Windows Security GUI.

**Comment by HotCakeX** [comment]
@dennyamarojr Hi, I've created a rationale page explaining what we talked about in this issue, link to it is mentioned at the top of the readme too. soon i will remove the warning about TLS from the script too and instead add a note in the readme, to keep things consistent.

https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md
