### ISSUE TITLE
[Bug]: AppControl manager update : "the specified blob does not exist"

### ISSUE THREAD

**Issue by eraldinho** [HotCakeX/Harden-Windows-Security#457]
### Tools category

AppControl Manager app

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

I'm trying to update AppControl Manager from version 1.3.0.0 to 1.6.0.0 with the automatic updater included but there is an error:

![image](https://github.com/user-attachments/assets/90531db3-ac25-491f-bdd9-8239de849b56)

My Windows version is 24H2 build 26100.2161

**Comment by HotCakeX** [comment]
Hi,
The updater system was improved between version 1.3 to 1.6 and that's why the error is shown. I'm sorry about that...

I made sure the updater would work from 1.3 -> 1.4 -> 1.5 -> 1.6, but 1.3 straight to 1.6 leaves some logic unavailable to the app so it doesn't know exactly what to do.

Please use [this](https://github.com/HotCakeX/Harden-Windows-Security/wiki/AppControl-Manager#how-to-install-or-update-the-app) again to install the latest version, it will automatically upgrade the existing app on your system:

```powershell
(irm 'https://raw.githubusercontent.com/HotCakeX/Harden-Windows-Security/main/Harden-Windows-Security.ps1')+'AppControl'|iex
```

This issue with the updater is a one-time thing, it won't happen again.

**Comment by eraldinho** [comment]
Hi, thanks for the quick response!

**Comment by HotCakeX** [comment]
No problem ^^ if that's okay i'm gonna close this now
