### ISSUE TITLE
Any help would be appreciated 

### ISSUE THREAD

**Issue by bluethedoor** [HotCakeX/Harden-Windows-Security#488]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

Hello, today I've been frequently using the 'Confirm-SystemCompliance' command and it's been working great with zero error up until a few minutes ago I started to experience the error shown below. I'm unsure of what I did to have make this happen, now Microsoft Store is appearing offline and windows is having an error with giving me updates. The only thing working is my browser.

![Error](https://github.com/user-attachments/assets/00cfbac4-82dd-4eb8-b827-c2483fa295d9)

### Error Details

```console
Invoke-RestMethod: Exception of type 'System.Net.InternalException' was thrown. -2146892963
```

**Comment by HotCakeX** [comment]
Hi,
First of all to be clear, this problem has nothing to do with the Harden Windows Security module.

Doing a quick Bing search, it appears that you modified your system in a way that it is preventing certain connections and TLS versions from successfully connecting.
https://stackoverflow.com/questions/41861378/initializesecuritycontext-returned-code-2146892963

I know for a fact that the module doesn't do it, so what i can suggest to you is remembering what other tool you used and try to revert it back.

Additionally, `Confirm-SystemCompliance` doesn't make any changes to the system, it only retrieves system details in order to display them to you.

I can suggest something else to try, delete everything under this registry path, including all of the sub-folders, then restart the system.

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\
```

Your browser is working because it has its own TLS stack and is unaffected by the system's TLS configurations.

**Comment by bluethedoor** [comment]
Hi again, I'm sorry for wasting your time. I realize now that I made a mistake while adjusting my ECC curve order. I've corrected the issue, and I appreciate your help. Thank you, and I'm sorry for the trouble.

**Comment by HotCakeX** [comment]
@bluethedoor no worries, thanks for letting me know and glad you got it resolved!
