### ISSUE TITLE
MDAV Exploit Protection policy

### ISSUE THREAD

**Issue by rafalfitt** [HotCakeX/Harden-Windows-Security#49]
https://github.com/Harvester57/Exploit-Protection-policy
https://github.com/milgradesec/windows-settings/blob/main/ExploitGuard/ExploitSettings.xml

**Comment by HotCakeX** [comment]
Hi,
I tried modifying the default Exploit Protection settings of Windows a couple of months ago but I remember not getting the right results and was having lots of compatibility issues.

These are really sensitive things that need extensive trial and error and testing to make sure they don't crash programs or even the OS itself as a result, so it's gonna take some time to verify how the built-in Windows programs and executables behave.

I'm not sure whether it's possible to automatically verify an executable is compatible with a specific Exploit Protection feature or not, it'd speed up the verification process a lot.

I can also think about the possibility that a program might be compatible with an Exploit Protection feature right now but the next version of it might crash.

**Comment by pl4nty** [comment]
EMET/Exploit Protection has unlimited scope and compat verification can be painful for certain mitigations. Some require binary support though, which could be checked automatically (CFG, CET Shadow Stack, etc). Audit mode is helpful too if centralised logging is available.

Most implementations I've seen have focused on apps that process untrusted input eg browsers, Office/Acrobat, 7zip/NanaZip. Would that be a suitable approach here?

**Comment by pl4nty** [comment]
It's not robust, but this works:

```PowerShell
dumpbin /headers /loadconfig .\msedge.exe | sls "Control Flow Guard", "CF Instrumented", "FID table present"
```

Could do `.Matches.Length -eq 3`, but individual checks with `sls -Quiet` would be better imo

**Comment by HotCakeX** [comment]
@pl4nty Thank you!

Yes, I think only configuring individual apps that are not system components is safer option, but since this script is general purpose I'm not sure how we can know which programs users have installed when running the script. Will have to prompt user for confirmation before running each of the categories i think.

Edge for example [has some exploit protection](https://support.microsoft.com/en-us/microsoft-edge/enhance-your-security-on-the-web-with-microsoft-edge-b8199f13-b21b-4a08-a806-daed31a1929d) features by default

[Hardware-enforced Stack Protection](https://techcommunity.microsoft.com/t5/windows-kernel-internals-blog/developer-guidance-for-hardware-enforced-stack-protection/ba-p/2163340) and [Arbitrary Code Guard (ACG)](https://docs.microsoft.com/microsoft-365/security/defender-endpoint/exploit-protection-reference?view=o365-worldwide#arbitrary-code-guard)

Edge also has [code integrity guard](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#configure-browser-process-code-integrity-guard-setting) but available through a policy that requires AD/AAD.

**Comment by HotCakeX** [comment]
This is the result for Edge executable

```
            00010500 Guard Flags
                       CF instrumented
                       FID table present
                       Long jump target table present
```

CF instrumented means that the binary file has been compiled with the /guard:cf option, which enables Control Flow Guard (CFG) for the code. CFG is a security feature that prevents exploits from hijacking the control flow of the program by checking the validity of indirect call targets at runtime.

FID table present means that the binary file has a GuardCFFunctionTable attached to the load configuration directory, which is a sorted list of relative virtual addresses (RVA) that contain information about valid CFG call targets. These are, generally speaking, address taken function symbols. An image that wants CFG enforcement must enumerate all address taken function symbols in its GFIDS table.

Long jump target table present means that the binary file has a GuardCFLongJumpTargetTable attached to the load configuration directory, which is a sorted list of RVAs that are valid long jump targets. If a long jump target module sets IMAGE_GUARD_CF_LONGJUMP_TABLE_PRESENT in its GuardFlags field, then all long jump targets must be enumerated in the LongJumpTargetTable.


Also system informer can show the exploit protections applied to each running process 

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/d66a3840-5e4c-4eff-bde9-aa309cd33c5d)
![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/9bd97c0b-16c4-491d-a771-279fead7c2ea)

**Comment by HotCakeX** [comment]
This is the setting that works with Edge and loads websites fine, haven't done extended testing yet to see if it crashes after running with many tabs and for many hours

```xml
<AppConfig Executable="C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe">
<DEP Enable="true" EmulateAtlThunks="true"/>
<ASLR ForceRelocateImages="true" RequireInfo="true" BottomUp="true" HighEntropy="true"/>
<StrictHandle Enable="true"/>
<ExtensionPoints DisableExtensionPoints="true"/>
<ControlFlowGuard Enable="true" SuppressExports="false" StrictControlFlowGuard="true"/>
<SignedBinaries MicrosoftSignedOnly="true" AllowStoreSignedBinaries="true" Audit="false" AuditStoreSigned="false" EnforceModuleDependencySigning="true"/>
<Fonts DisableNonSystemFonts="true" AuditOnly="false" Audit="false"/>
<ImageLoad BlockRemoteImageLoads="true" AuditRemoteImageLoads="false" BlockLowLabelImageLoads="true" AuditLowLabelImageLoads="false"/>
<SEHOP Enable="true" TelemetryOnly="false"/>
<Heap TerminateOnError="true"/>
</AppConfig>
```

Anything else either prevents Edge from loading or loads but gets stuck with 100% CPU usage.

With System Informer, I can see child processes of msedge.exe having different process mitigations. some of them have a lot more and some of them have only few. Probably because of the Edge policies I applied for sandboxing different components of it.

Gonna need some more info understanding the whole thing and how the Edge policies work with MDAV exploit protection features, which one takes priority etc.

**Comment by HotCakeX** [comment]
If anyone wants to help testing this configuration for extended periods, here is the PowerShell code

```powershell
Set-ProcessMitigation -Name 'msedge.exe' -Enable DEP,
EmulateAtlThunks,
BottomUp,
ForceRelocateImages,
RequireInfo,
HighEntropy,
StrictHandle,
DisableExtensionPoints,
CFG,
StrictCFG,
MicrosoftSignedOnly,
AllowStoreSignedBinaries,
EnforceModuleDependencySigning,
DisableNonSystemFonts,
BlockRemoteImageLoads,
BlockLowLabelImageLoads,
SEHOP,
TerminateOnError
```

Using PowerShell is better than xml file importing imo because this way the hardening script will only touch specific executables and won't overwrite any other possible existing user/system settings.

**Comment by HotCakeX** [comment]
The final exploit protection/process mitigations that I'm going to add to the script if I continue seeing no issues. If anyone has suggestions for including other processes please let me know.

Edge opens PDFs using Adobe Acrobat engine.

Working on Nanazip

@pl4nty which process mitigations do you think are suitable for M365/Office apps ?

```powershell
# Enable Mandatory ASLR Exploit Protection system-wide
set-processmitigation -System -Enable ForceRelocateImages

# Enable Exploit Protection/process mitigations for Microsoft Edge - applies to all Edge channels
Set-ProcessMitigation -Name 'msedge.exe' -Enable DEP,
EmulateAtlThunks,
BottomUp,
ForceRelocateImages,
RequireInfo,
HighEntropy,
StrictHandle,
DisableExtensionPoints,
CFG,
StrictCFG,
MicrosoftSignedOnly,
AllowStoreSignedBinaries,
EnforceModuleDependencySigning,
DisableNonSystemFonts,
BlockRemoteImageLoads,
BlockLowLabelImageLoads,
SEHOP,
TerminateOnError,
UserShadowStack

# Enable Exploit Protection/process mitigations for other system components
Set-ProcessMitigation -Name "mscorsvw.exe" -Enable DisableExtensionPoints
Set-ProcessMitigation -Name "ngen.exe" -Enable DisableExtensionPoints
Set-ProcessMitigation -Name "ngentask.exe" -Enable DisableExtensionPoints
Set-ProcessMitigation -Name "PrintDialog.exe" -Enable DisableExtensionPoints
Set-ProcessMitigation -Name "SystemSettings.exe" -Enable DisableExtensionPoints
Set-ProcessMitigation -Name "runtimebroker.exe" -Enable DisableExtensionPoints
Set-ProcessMitigation -Name "C:\Windows\System32\vmcompute.exe" -Enable CFG, SuppressExports, StrictCFG
Set-ProcessMitigation -Name "C:\windows\system32\vmwp.exe" -Enable CFG, SuppressExports, StrictCFG

# Enable Exploit Protection/process mitigations for Quick Assist
Set-ProcessMitigation -Name "QuickAssist.exe" -Enable DisableExtensionPoints,                
StrictHandle,
BlockDynamicCode,
MicrosoftSignedOnly,
AllowStoreSignedBinaries,
EnforceModuleDependencySigning,
DisableNonSystemFonts,
BlockRemoteImageLoads,
BlockLowLabelImageLoads,
EnableExportAddressFilter,
EnableExportAddressFilterPlus,
EnableImportAddressFilter,
EnableRopStackPivot,
EnableRopCallerCheck,
EnableRopSimExec,
UserShadowStack,
UserShadowStackStrictMode -Disable AllowThreadsToOptOut
```

**Comment by HotCakeX** [comment]
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/v2023.6.29

**Comment by Harvester57** [comment]
You should take all the documentation about Exploit Protection with a big pinch of salt, because ACG (BlockDynamicCode) can be enabled just fine within a XML file:

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/7060295/5f08472d-3db4-4ccd-8536-c98e62c354f4)

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/7060295/893b3e8d-7d9a-446e-b0f4-570b184ec40f)


A lot could be said about the table describing the mitigations (cf. https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/customize-exploit-protection?view=o365-worldwide#exploit-protection-mitigations), where most of the settings described as "App-level only" can indeed be enabled at system-level. In fact, any setting that is listed under `Get-ProcessMitigation -System` can be configured at system-level, whatever the documentation is saying about it.

**Comment by HotCakeX** [comment]
@Harvester57 In that case we should open issues for that doc page

I don't think that paragraph is referring to ACG though, but only this part 
> Can optionally allow thread opt-out and allow remote downgrade (configurable only with PowerShell).

The bigger issue i had with it was overriding previously set user process mitigations, but with the current method the script only touches individual program names* and*  individual mitigations for them, it's the most specific method imho

I put them in CSV for easier verification too

**Comment by HotCakeX** [comment]
M365 apps including OneDrive added: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/v2023.08.28
