### ISSUE TITLE
Security baseline for Microsoft Edge

### ISSUE THREAD

**Issue by rafalfitt** [HotCakeX/Harden-Windows-Security#50]
https://techcommunity.microsoft.com/t5/microsoft-security-baselines/security-baseline-for-microsoft-edge-version-114/ba-p/3839728

**Comment by HotCakeX** [comment]
Hi @rafalfitt 
Thanks for brining this up ^^

The reason I didn't use security baselines for Microsoft Edge and instead use registry to apply the policies is because of this:

> This policy is available only on Windows instances that are joined to a Microsoft Active Directory domain, Windows 10 Pro or Enterprise instances that enrolled for device management, or macOS instances that are that are managed via MDM or joined to a domain via MCX.

There are many important security measures that require AAD or Domain Controller joined PCs. All of them are [mentioned here](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-policies).

I think the reason is that they can be potentially abused by registry or Group Policy modifications by 3rd party apps or malware.

I just tried this, injected the latest the Edge 114 Group Policy ADMX files and then applied the Edge 114 Security baseline, this is the result:

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/a226176d-9ccd-4cf1-af44-212d64a446cc)

Those are the items that can't be applied without a domain controller or AAD.

There is another issue about using security baselines for Microsoft Edge. The Group Policy ADMX files aren't included in Windows by default. They are updated every month so users would have to make sure they run the script after each Edge version release to keep their ADMX files up to date and prevent any issues.

Some of the policies in the Security baseline for Microsoft Edge are applied by default, the policies just make sure non-Admins in corporations etc. can't change them. However, the Harden Windows Security script assumes everyone already has Admin privileges, so it just automatically configures the security features and isn't intended to prevent users with Admin privileges from changing their own device's settings.

Finally, as you can see in the screenshot, the Security baseline uses a policy that blocks all the extensions by default and requires administrators to explicitly add each extension that the users require to use in an allow list.

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/6e3458fe-8387-4893-822d-c300456725c8)

I hope you agree with me that it's not practical to use this policy on personal computers. 😇

**Comment by HotCakeX** [comment]
> 1. "There are many important security measures that require AAD or Domain Controller joined PCs." - yes, you are right.
> 2. "The Group Policy ADMX files aren't included in Windows by default. They are updated every month" - you are right
>    "so users would have to make sure they run the script after each Edge version release to keep their ADMX files up to date and prevent any issues." - IMHO this is not true - AFAIK the GPO settings are stored in registry.pol (if done using .ADMX + gpedit.msc) and/or in registry (after application), so the updated ADMX is not really needed.
> 
> if all/most recommended settings are applied in the script (I've not checked so far), perhaps only a mention of "Security baseline for Microsoft Edge" is needed on https://github.com/HotCakeX/Harden-Windows-Security#edge-browser-configurations

Oh yes, you're right in #2, the script could download and install latest ADMX files first and then apply the latest Edge Security baselines, every time the Edge category was run, so no issue with keeping the local ADMX files up to date.

I should check the new policies again and if any of them improves security and isn't being applied by default in Edge I'll add it to the script, will also change the Readme like you suggested. 👍

**Comment by rafalfitt** [comment]
IMHO:
.ADMX is *only* needed if you use GPEDIT.MSC
if you have a registry.pol (it will be applied to registry when booting by Group Policy Client service) or settings in registry (in Policies key) - you can ignore missing/outdated .ADMX

**Comment by HotCakeX** [comment]
> IMHO: .ADMX is _only_ needed if you use GPEDIT.MSC if you have a registry.pol (it will be applied to registry when booting by Group Policy Client service) or settings in registry (in Policies key) - you can ignore missing/outdated .ADMX, no need to download .ADMX

Awesome, thank you! I just tried applying the Edge Security baseline without injecting the ADMX files first and it worked! not sure if it's best practices this way but it works :)

So just to make sure, you still suggest to add Edge security baselines to the script with everything mentioned before?

**Comment by rafalfitt** [comment]
yes, I do suggest, as it makes a nice complete set:
Microsoft Windows security baseline
Microsoft 365 Apps security baseline
Microsoft Edge security baseline

**Comment by HotCakeX** [comment]
> yes, I do suggest, as it makes a nice complete set: Microsoft Windows security baseline Microsoft 365 Apps security baseline Microsoft Edge security baseline

But what do you suggest to do about the problems I mentioned?

**Comment by HotCakeX** [comment]
> there is no SLA - IMHO "best effort" is good enough, as we don't want to over-complicate/introduce more dependencies/etc.: policies are set in the registry, the result is outside our scope of work (require AAD or Domain Controller joined PCs or other limitations).

There is no signed agreement for service level, true, but since I use this too i don't want best effort, i want the best.

Going to close this issue for the following reasons:

1. Important settings that are also included in Edge security baselines require AAD or domain controller. So, using Edge security baseline in standalone mode doesn't provide the same security.
2. Edge security baseline has policies that cause a lot of inconvenience and do more bad than good when it comes to personal users. Those policies are shown in the screenshots above, such as a policy that blocks all of the extensions.
3. Using Edge security baseline would require a lot of overrides due to the reasons mentioned earlier, making it essentially useless.
4. The script applies similar security policies and even more, using registry keys, they have the same effect. If there is any particular policy that you think should be added (and it's not already enabled by default in Edge) then please open a new issue for it.

Thank you! have a good one!

**Comment by HotCakeX** [comment]
Just pushed an update to the Edge category

https://github.com/HotCakeX/Harden-Windows-Security/commit/42e0ba61a415de594f994a20a1477efbc77f93a1

https://github.com/HotCakeX/Harden-Windows-Security#edge-browser-configurations

**Comment by starchturrets** [comment]
You don't need to do regedits to set edge policies, you can simply point `LGPO.exe` at a `.pol` file - the only thing you'll need the admx files for is if you want to override the policies manually. Or if you want `GPReport.html` to have the proper policy names displayed.

**Comment by starchturrets** [comment]
Because the repo says 

> The script primarily uses Group policies, the Microsoft recommended way of configuring Windows. It also uses PowerShell cmdlets where Group Policies aren't available, and finally uses [a few registry keys](https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Payload/Registry.csv) to configure security measures that can neither be configured using Group Policies nor PowerShell cmdlets.

So that makes it seem like if it was possible to use a GPO instead of a registry key, it would be better.

**Comment by Mrkuff** [comment]
From what I see, here's a list of policies who's working only with Microsoft Entra profile. (No personal MSA)
https://learn.microsoft.com/en-us/DeployEdge/edge-learnmore-personal-browser-policies

This is a filtered list of policies supposed to include this tag: 
**>Applies to a profile that is signed in with a Microsoft account: No<**

Exemple for AllowGamesMenu :

Supported features:
Can be mandatory: Yes
Can be recommended: No
Dynamic Policy Refresh: No - Requires browser restart
Per Profile: Yes
**Applies to a profile that is signed in with a Microsoft account: No**    No = Microsoft Entra

Within the "Microsoft Edge v128 Security Baseline" there's 19 policies.  Within these, 3 are in this list.

ExtensionInstallBlocklist : Control which extensions cannot be installed
NativeMessagingUserLevelHosts : Allow user-level native messaging hosts (installed without admin permissions)
SSLErrorOverrideAllowed : Allow users to proceed from the HTTPS warning page

If this filtered list is correct, ExtensionInstallBlocklist = *, with personal MSA account, it's ignored.

And they are not giving the "Error - This policy is blocked; its value will be ignored" within the console.

If you are looking at the one in error, like "SmartScreenEnabled", it's not in this "filtered list". This got the
**Applies to a profile that is signed in with a Microsoft account: Yes** (MSA ok) but in the description we read the warning: 

This policy is available only on Windows instances that are joined to a Microsoft Active Directory domain, Windows 10 Pro or Enterprise instances that enrolled for device management, or macOS instances that are that are managed via MDM or joined to a domain via MCX.

Maybe they need to update it? at "Applies to a profile that is signed in with a Microsoft account: NO"

If the "ExtensionInstallBlocklist" is ignored and the 16 other policies are applied, I guess using GPO template instead of registry wouldn't be that bad.  Just be aware that certain policies apply for domain users only.  So forget about it blocking the "Shopping in Microsoft Edge" locally.

**Comment by Mrkuff** [comment]
So they are wrong when they say : This policy is available only on Windows instances that are joined to a Microsoft Active Directory domain, Windows 10 Pro or Enterprise instances that enrolled for device management, or macOS instances that are that are managed via MDM or joined to a domain via MCX.  For me they are in error when using a Local Admin Account (SID 500 in this case) 

![Image](https://github.com/user-attachments/assets/eed2cb3d-7866-406d-b57b-89a3ae49d835)

**Comment by HotCakeX** [comment]
@Mrkuff If we use group policy then we'll have to use overrides for them to enable browser extensions etc. bcz the policies are tuned for work environment and not regular end users. That's one of the issues mentioned in the thread.

**Comment by Mrkuff** [comment]
@HotCakeX you're right.  I've just tested the policy "ExtensionInstallBlocklist" with a session with MSA and it apply the restriction, even if the documentation clearly stated that "Applies to a profile that is signed in with a Microsoft account: No"  

It's a real mess!!

The real reason why I'm not a fan of registry hacking for GPO it's because sometimes, just hacking the registry give an incomplete configuration.  For exemple, "AudioSandboxEnabled".  

If you apply it by registry only, when you look in the Local GPO console, this does not appear as configured.  If you remove it from the registry, then configure it within the LGPO MMC, it appears in the registry but if you delete it in the registry, the LGPO MMC still show it to you as configured...

So is it really configured when applied by reg hack?  You can see it in the console (and probably the gpresult as well).
We see the policy in edge://policy/ as true so it's prolly ok, but..

![Image](https://github.com/user-attachments/assets/e3b6c6c8-ef90-4465-899b-4822289d6750)

**Comment by Mrkuff** [comment]
the other way around, if I hack the registry only, the config never appears within the LGPO MMC, after a reboot and a gpupdate /force

![Image](https://github.com/user-attachments/assets/bb6ffbba-4d90-449f-9427-f32d99df8df1)

**Comment by HotCakeX** [comment]
It's expected when you apply by registry then Group policy won't show it because Group Policies are stored somewhere else: `C:\WINDOWS\System32\GroupPolicy`

The mess you noticed is exactly why i've been using registry keys for Edge. For over a year it's been working fine and they rarely need any changes.

If there are new security related policies that need to be added to the Edge category please lmk so i can add them.

**Comment by Mrkuff** [comment]
> If there are new security related policies that need to be added to the Edge category please lmk so i can add them.

Yes Ma'am !
