### ISSUE TITLE
Chrome Browser Enterprise Security Configuration - perhaps worth adding?

### ISSUE THREAD

**Issue by rafalfitt** [HotCakeX/Harden-Windows-Security#51]
Google Chrome is quite popular, so IMHO it is worth protecting:
https://support.google.com/chrome/a/answer/9710898?hl=en

**Comment by rafalfitt** [comment]
+ https://cloud.google.com/blog/products/chrome-enterprise/new-benchmarks-securing-chrome-center-internet-security

**Comment by rafalfitt** [comment]
yes, but:
Creating the policy entries for Google Chrome will not decrease security, and it can even increase both for group #1 and group #2.

**Comment by HotCakeX** [comment]
> yes, but: Creating the policy entries for Google Chrome will not decrease security, and it can even increase both for group #1 and group #2.

I see, well, Group #1 are being managed by their own administrators in different ways, they have their domain controller or AAD (CSP), Security baselines are offered as CSP in Intune for them.

Group #2 have the choice to switch over to Edge since nothing is forcing them to use Chrome. So, with respect I'm going to continue focusing on Edge only.

**Comment by rafalfitt** [comment]
"Security for [Organizations, Enterprises](https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md#-what-about-other-enterprise-security-) and Highly secure personal users" - so IMHO Google Chrome might be in scope for group #1 and #2😋

**Comment by HotCakeX** [comment]
> "Security for [Organizations, Enterprises](https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md#-what-about-other-enterprise-security-) and Highly secure personal users" - so IMHO Google Chrome might be in scope for group #1 and #2😋

https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md#-important-considerations

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/8e787ecc-fa81-4fc6-aeef-32912ee7b3c7)

**Comment by HotCakeX** [comment]
I just pushed an update to the Edge category
https://github.com/HotCakeX/Harden-Windows-Security/commit/42e0ba61a415de594f994a20a1477efbc77f93a1

https://github.com/HotCakeX/Harden-Windows-Security#edge-browser-configurations

Spent pretty much the whole day reviewing every single policy available for Edge browser and will be reviewing every new policy from now on and will add them if necessary. They are policies that aren't being applied by default or their default state isn't desired.

Changed one of them too: The Edge policies no longer enforce Cloudflare DNS over HTTPS and instead use the OS's DNS over HTTPS. This change is being made to allow MDAG (Microsoft Defender Application Control) to be able to connect to the Internet. With Edge enforcing DoH, it wouldn't be able to connect and would show DNS related errors. Windows 11's system wide DNS over HTTPS settings also apply to MDAG connections as well as any other apps, so they are more secure and preferred. (Going to write more about this)

The reason I caught that issue or the other one with primary password, is because I use Edge 24/7/365 on all devices and that allows me to constantly check and verify all the policies and change them if there is an issue before anyone else.

I can't do the same for Chrome or any other browser, because I don't use them. That along with other reasons already mentioned, should hopefully be enough for not considering this issue, so going to close it with this comment.

Thank you!

**Comment by Ganwtrs** [comment]
> @HotCakeX 
> https://github.com/HotCakeX/Harden-Windows-Security/blob/main/Rationale.md#-important-considerations
> 
> ![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/118815227/8e787ecc-fa81-4fc6-aeef-32912ee7b3c7)

I understand the reasons for why a Google Chrome guide has not been made! I would just like to point out a few things.

Microsoft Edge is already based on Google’s Chromium, so using Google Chrome doesn’t trust a third party that much more compared to Edge.

[This guide](https://github.com/RKNF404/chromium-hardening-guide?tab=readme-ov-file#popular-options) mentions some pros and cons for Chrome and Edge security; it’s not completely one sided. (It might also be helpful for Edge security policies)
