### ISSUE TITLE
Smart App Control does not actually need Optional Diagnostic data to function, despite what Microsoft Docs say

### ISSUE THREAD

**Issue by starchturrets** [HotCakeX/Harden-Windows-Security#94]
Proof:

![image](https://github.com/HotCakeX/Harden-Windows-Security/assets/37842965/627b117a-7afc-4bc4-b65c-1afd44171ee4)

What *is* forced on is the Check Apps and Files setting, as well as the Potentially unwanted app blocking setting under the reputation based protection section in Windows Security.

I would recommend not forcing this on in the script, as many users are likely to be uncomfortable trusting Microsoft with that much data, as opposed to required diagnostics which is (mostly) hardware data.

> Additional data about the websites you browse, how Windows and apps are used and how they perform. This data also includes data about device activity, and enhanced error reporting that helps Microsoft to fix and improve products and services for all users.

https://learn.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#diagnostic-data-settings

**Comment by starchturrets** [comment]
> Seeing the toggle is on doesn't mean it works as intended. The [official page](https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003) says it's required so I'm not going to make any assumptions and break functionalities, I know other people do it and then they wonder what went wrong and then blame Windows OS for their own mistake and misconfiguration.

I've noted it block parts of tor browser (with notification), unknown apps, and lnk files with MOTW on them - seems to be functioning as expected, either with optional diagnostics off or on. I'm not 100% sure, but if it were the case that optional diagnostics were required for the ISG to function (and not just for evaluation mode to...evaluate), wouldn't it just force that toggle on like the check app and files one? I think this is supported by the WDAC docs page on ISG not saying anything about having to turn on optional diagnostics OS wide.

 Also, have you had reports from others that SAC wasn't working with optional diagnostics disabled?
 
 > Trusting or not trusting Microsoft is not in the scope of this repository. There are a lot of FUDs on the Internet about these subjects.

Fair enough, though imo trust isn't a binary thing. One can use MS products without buying into their entire cloud ecosystem and whatnot.

**Comment by HotCakeX** [comment]
what I can do is make it optional with a note saying it's required for Smart App Control, that way the miscellaneous category doesn't enable it by default.

I don't collect reports on that though. There is a reason the document says it's required, if that changes then it will change here too, but 

WDAC can use ISG as a policy rule option but Smart App Control works very [differently](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-for-Lightly-Managed-Devices#security-considerations). It's powerful and great addition to the security stack, I'd suggest using it if it doesn't block important stuff.

**Comment by starchturrets** [comment]
Alright, thanks.

> WDAC can use ISG as a policy rule option but Smart App Control works very [differently](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDAC-for-Lightly-Managed-Devices#security-considerations). It's powerful and great addition to the security stack, I'd suggest using it if it doesn't block important stuff.

Oh yeah Smart App Control also does the thing where it blocks "dangerous file types" like LNK/ISO files, so long as they have MOTW removed. WDAC doesn't currently have an equivalent to that for some reason. I actually did want to use SAC in conjunction with WDAC but unfortunately it seems custom policies can only make it more restrictive, not less. Which is a pity.

**Comment by starchturrets** [comment]
From my testing in a VM with a bunch of apps and it's a *lot* more lenient than I remember it being. Though then again I get pretty much all my apps from winget so I was hard pressed to find a low reputation executable.

> Custom policies can be anything you want, you can allow everything or you can allow nothing, it's your playground and you set the rules :)

Yeah I can allow everything, but since it runs alongside the SAC policy it can't override if SAC is blocking something - though given how lenient I've found it to be with winget apps this might not be as much of an issue. Once I get around to doing a reinstall I'll prolly use both simultaneously in order to benefit from restrictive WDAC + dangerous file type blocking.

**Comment by HotCakeX** [comment]
Winget is good, checks the hash of the apps, they're usually popular so ISG has more info about them. I also notice that some of the unsigned files in my apps that used to get blocked are now allowed, they probably proved that they are trustworthy enough, but from the description of the AI, if the file exhibits malicious behavior at any point it should be blocked again.

Oh i see, you were trying to create supplemental policy for SAC? I think the reason it can't be done is because SAC's policy that gets implemented is MS signed so the supplemental policy you want to deploy to allow a custom file in SAC must also be signed otherwise it's ignored.

**Comment by HotCakeX** [comment]
Hi, I just released an update that includes this new behavior:

Optional diagnostic data is only automatically turned on if Smart App Control is already turned on OR user chooses to turn Smart App Control on, otherwise it will show a prompt to enable it if Smart App Control is not turned off.
Also, the prompt is shown right after Smart App Control's prompt and no longer in the miscellaneous category.

Pull request: https://github.com/HotCakeX/Harden-Windows-Security/pull/98
Release: https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/v2023.08.30

**Comment by pingu-the-penguin** [comment]
I believe Optional Diagnostic Data can be turned off if Smart App Control is already enabled. If Smart App Control is on evaluation mode, then Smart App Control needs Optional Diagnostic Data to be able to make a decision. This is why the documentation mentions the need for Optional Diagnostic Data during the setup process as otherwise, Smart App Control would be turned off (since it can't get through Evaluation).

If someone already decides to use the HSS app and force enable Smart App Control, there is no need for Optional Diagnostic Data since in that case, the user is not in Evaluation mode anymore. I have not seen any documentation regarding Optional Diagnostic Data being required for good functioning of Smart App Control. 

https://learn.microsoft.com/en-my/answers/questions/5866370/smart-app-control-and-send-optional-diagnostic-dat

**Comment by pingu-the-penguin** [comment]
Hello, I didn't want to create a new issue about this as to not flood the repo but I was wondering if this change could be considered?

In addition to the information above, the only mention of Smart App Control and Optional Diagnostic data is in the FAQ section, namely this quote:

> > Why is Smart App Control turned off?
> There are multiple reasons why Smart App Control could be turned off, for example:
> 
> Your device is enterprise-managed or developer-mode has been configured.
> 
> During [evaluation mode](https://support.microsoft.com/en-au/windows/smart-app-control-frequently-asked-questions-285ea03d-fa88-4d56-882e-6698afdb7003#bkmk_eval) we determined that you weren't a good candidate for Smart App Control.
> 
> It was turned off manually by you or another user signed into your machine.
> 
> Your device is running Windows in S mode. You'll need to turn S mode off, then reset your PC, to enter evaluation mode.
> 
> You have [optional diagnostic data](https://support.microsoft.com/en-au/windows/diagnostics-feedback-and-privacy-in-windows-28808a2b-a31b-dd73-dcd3-4559a5199319) in Windows turned off. If you want to turn Smart App Control on, you'll need to reset this PC, or reinstall Windows, and select Send optional diagnostic data during the setup process.
> 
> Recent Windows updates allow Smart App Control to be enabled within the Windows Security App without requiring a clean installation.

This FAQ entry corroborates the Microsoft AI-Generated forum response in the first link and seems like a reasonable way to interpret it. Additionally, Optional Diagnostic Data is only given as a reason for why Smart App Control could be off, and the remedy being a clean installation. Later on in the entry it says that recent Windows versions are able to turn Smart App Control on without ever requiring a clean installation.

I think it would make sense to decouple Smart App Control and Optional Diagnostic Data in the HSS app as well as potentially removing the Optional Diagnostic Data section as it does not seem to have any security improvement or affect any other components. I could be wrong on this specific point though so I'd appreciate if incorrect information could be corrected.

**Comment by HotCakeX** [comment]
> Hello, I didn't want to create a new issue about this as to not flood the repo but I was wondering if this change could be considered?
> 
> In addition to the information above, the only mention of Smart App Control and Optional Diagnostic data is in the FAQ section, namely this quote:
> 
> > > Why is Smart App Control turned off?
> > > There are multiple reasons why Smart App Control could be turned off, for example:
> > 
> > 
> > Your device is enterprise-managed or developer-mode has been configured.
> > During [evaluation mode](https://support.microsoft.com/en-au/windows/smart-app-control-frequently-asked-questions-285ea03d-fa88-4d56-882e-6698afdb7003#bkmk_eval) we determined that you weren't a good candidate for Smart App Control.
> > It was turned off manually by you or another user signed into your machine.
> > Your device is running Windows in S mode. You'll need to turn S mode off, then reset your PC, to enter evaluation mode.
> > You have [optional diagnostic data](https://support.microsoft.com/en-au/windows/diagnostics-feedback-and-privacy-in-windows-28808a2b-a31b-dd73-dcd3-4559a5199319) in Windows turned off. If you want to turn Smart App Control on, you'll need to reset this PC, or reinstall Windows, and select Send optional diagnostic data during the setup process.
> > Recent Windows updates allow Smart App Control to be enabled within the Windows Security App without requiring a clean installation.
> 
> This FAQ entry corroborates the Microsoft AI-Generated forum response in the first link and seems like a reasonable way to interpret it. Additionally, Optional Diagnostic Data is only given as a reason for why Smart App Control could be off, and the remedy being a clean installation. Later on in the entry it says that recent Windows versions are able to turn Smart App Control on without ever requiring a clean installation.
> 
> I think it would make sense to decouple Smart App Control and Optional Diagnostic Data in the HSS app as well as potentially removing the Optional Diagnostic Data section as it does not seem to have any security improvement or affect any other components. I could be wrong on this specific point though so I'd appreciate if incorrect information could be corrected.

It honestly doesn't say that when SAC is on we can safely turn off optional diagnostics data. All it says for certain is that it is needed for SAC, but doesn't say it's okay to turn it off when it's switched on.

I don't wanna risk it by interpreting the document wrongly, especially since optional diagnostic data is not normally applied on the system in Microsoft Defender category unless user explicitly chooses SAC option, and it doesn't cause harm and user can simply uncheck it if they want to. So the app is currently configured based on the last known good info and i think it's safer to change this state only based on facts. I can definitely ask around and get more info about this.

There aren't much explanations publicly from Microsoft about SAC and how it works, there are write ups from 3rd parties though that are often older and not up to date, like this one: https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/Studies/Smart_App_Control/Studie_Smart_App_Control.pdf?__blob=publicationFile&v=2

and things change a lot in the OS from one update to another whereas the writeups are only true for the specific OS build that was tested.

Maybe one brute force way to learn more about SAC is watching the OS traffic for a period of time with Wireshark while it's in eval mode vs On mode and see if there is any difference in the amount or type of data sent/received.

What i'm sure about is that SAC needs active internet connection to work properly, but not sure whether the data it sends/receives is through a pipeline other than the optional diagnostic data or not.
